/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivitiesModal: typeof import('./src/components/ActivitiesModal.vue')['default']
    CreateActivityModal: typeof import('./src/components/CreateActivityModal.vue')['default']
    CreateClientModal: typeof import('./src/components/CreateClientModal.vue')['default']
    CreateProjectModal: typeof import('./src/components/CreateProjectModal.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    EditActivityModal: typeof import('./src/components/EditActivityModal.vue')['default']
    EditClientModal: typeof import('./src/components/EditClientModal.vue')['default']
    EditProjectModal: typeof import('./src/components/EditProjectModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListClient: typeof import('./src/components/ListClient.vue')['default']
    ListClients: typeof import('./src/components/ListClients.vue')['default']
    ListDashboard: typeof import('./src/components/ListDashboard.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
  }
}
