version: '3.8'

services:
  app:
    image: openjdk:21-jdk
    container_name: gestao_projetos_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gestao_projeto
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: gestao_projetos_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gestao_projeto
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
