spring.application.name=srv-gestao-projetos

#APP CONFIG
server.servlet.context-path=/srv-gestao-projetos
server.port=8081

#DB
spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_projetos
spring.datasource.username=postgres
spring.datasource.password=123123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Swagger Config
springfox.documentation.swagger-ui.enabled=true
springfox.documentation.swagger-ui.base-url=/srv-gestao-projetos/swagger-ui.html
